sudo: false
language: php
php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_install:

script:
    cd plugins/versionpress && composer install && ./vendor/bin/phpcs --standard=ruleset.xml
