version: '3.6'
services:

  wordpress:
    image: versionpress/wordpress:php7.2-apache
    ports:
      - 8088:80
    volumes:
      - ./plugins/versionpress:/var/www/html/wp-content/plugins/versionpress
      - ./dev-env/wp:/var/www/html
    links:
      - mysql
    environment:
      WORDPRESS_DB_PASSWORD: r00tpwd

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00tpwd

  adminer:
    image: adminer
    ports:
      - 8099:8080
    links:
      - mysql:db

  # Just test runner. See `tests-with-wordpress` for test runner with WordPress.
  tests:
    image: versionpress/wordpress:cli
    volumes:
      - ./dev-env/wp-for-tests:/var/www/html
      - ./dev-env/test-logs:/var/opt/versionpress/logs
      - ./plugins/versionpress:/opt/versionpress:ro
      - ./ext-libs:/opt/ext-libs:ro
      - wpcli-cache:/var/www/.wp-cli
    working_dir: /opt/versionpress/tests
    command: ../vendor/bin/phpunit --verbose --colors -c phpunit.xml --testdox-text /var/opt/versionpress/logs/testdox.txt

    # Allow interactive session by running `docker-compose run --rm tests sh`
    stdin_open: true
    tty: true

  tests-with-wordpress:
    image: versionpress/wordpress:cli
    volumes:
      # Same volumes as in `tests-plain`
      - ./dev-env/wp-for-tests:/var/www/html
      - ./dev-env/test-logs:/var/opt/versionpress/logs
      - ./plugins/versionpress:/opt/versionpress:ro
      - ./ext-libs:/opt/ext-libs:ro
      - wpcli-cache:/var/www/.wp-cli
    links:
      - selenium-hub:selenium-hub
      - wordpress:wordpress
    working_dir: /opt/versionpress/tests
    command: ../vendor/bin/phpunit --verbose --colors -c phpunit.xml --testdox-text /var/opt/versionpress/logs/testdox.txt

    # Allow interactive session by running `docker-compose run --rm tests-with-wordpress sh`
    stdin_open: true
    tty: true

  selenium-hub:
    # Standalone Firefox is enough but could also be a full grid setup, hence the service name
    image: selenium/standalone-firefox

volumes:
  db_data:
  wpcli-cache:
