site_name: VersionPress Documentation
docs_dir: './docs/content/en'
repo_url: https://github.com/versionpress/versionpress
site_description: 'Welcome to VersionPress documentation. VersionPress itself is intuitive to use but some things like core concepts or installation details require more attention and are described here.'
copyright: '2018 VersionPress'
pages:
  - Home: 'index.md'
  - User:
    - Getting Started:
      - 'Getting Started Home': 'user/getting-started/index.md'
      - 'Basic Concepts': 'user/getting-started/concepts.md'
      - 'Installation and Uninstallation': 'user/getting-started/installation-uninstallation.md'
      - 'Configuration': 'user/getting-started/configuration.md'
      - 'Using VersionPress': 'user/getting-started/using-versionpress.md'
      - 'Developer Preview': 'user/getting-started/about-eap.md'
    - Feature Focus:
      - 'Feature Focus Home': 'user/feature-focus/index.md'
      - 'How VersionPress Works': 'user/feature-focus/how-versionpress-works.md'
      - 'Change Tracking': 'user/feature-focus/change-tracking.md'
      - 'Undo and Rollback': 'user/feature-focus/undo-and-rollback.md'
      - 'Searching History': 'user/feature-focus/searching-history.md'
      - 'External Plugins and Themes': 'user/feature-focus/index.md'
      - 'Custom project structure': 'user/feature-focus/custom-project-structure.md'
      - 'WP-CLI Commands': 'user/feature-focus/wp-cli.md'
      - 'Versioning Engine - Git': 'user/feature-focus/git.md'
      - 'Performance Considerations': 'user/feature-focus/performance.md'
    - Sync / Team Workflows:
      - 'Sync / Team Workflows Home': 'user/sync/index.md'
      - 'Concepts': 'user/sync/concepts.md'
      - 'Cloning a Site': 'user/sync/cloning.md'
      - 'Merging Sites': 'user/sync/merging.md'
    - 3rd Party Integrations:
      - '3rd Party Integrations Home': 'user/integrations/index.md'
      - 'Plugins': 'user/integrations/plugins.md'
      - 'Themes': 'user/integrations/themes.md'
      - 'Hosts': 'user/integrations/hosts.md'
    - Troubleshooting:
      - 'Troubleshooting Home': 'user/troubleshooting/index.md'
      - 'System Info Page': 'user/troubleshooting/system-info-page.md'
      - 'UI Not Loading': 'user/troubleshooting/ui-not-loading.md'
      - 'IIS': 'user/troubleshooting/iis.md'
  - Developer:
    - 'Developer Setup': 'developer/setup.md'
    - 'Plugin Support': 'developer/plugin-support.md'
    - 'Development Process': 'developer/development-process.md'
  - Release Notes:
    - 'Release Notes Home': 'release-notes/index.md'
    - 'Roadmap': 'release-notes/roadmap.md'
    - '4.0-beta Release Notes': 'release-notes/4.0-beta.md'
    - '4.0-alpha1 Release Notes': 'release-notes/4.0-alpha1.md'
    - '3.0.2 Release Notes': 'release-notes/3.0.2.md'
    - '3.0.1 Release Notes': 'release-notes/3.0.1.md'
    - '3.0 Release Notes': 'release-notes/3.0.md'
    - '2.2 Release Notes': 'release-notes/2.2.md'
    - '2.1.1 Release Notes': 'release-notes/2.1.1.md'
    - '2.1 Release Notes': 'release-notes/2.1.md'
    - '2.0.1 Release Notes': 'release-notes/2.0.1.md'
    - '2.0 Release Notes': 'release-notes/2.0.md'
    - '1.0.1 Release Notes': 'release-notes/1.0.1.md'
    - '1.0 Release Notes': 'release-notes/1.0.md'
    - '1.0-rc3 Release Notes': 'release-notes/1.0-rc3.md'
    - '1.0-rc2 Release Notes': 'release-notes/1.0-rc2.md'
    - '1.0-rc1 Release Notes': 'release-notes/1.0-rc1.md'
    - '1.0-beta2 Release Notes': 'release-notes/1.0-beta2.md'
    - '1.0-beta1 Release Notes': 'release-notes/1.0-beta1.md'
    - '1.0-alpha3 Release Notes': 'release-notes/1.0-alpha3.md'
    - '1.0-alpha2 Release Notes': 'release-notes/1.0-alpha2.md'
    - '1.0-alpha1 Release Notes': 'release-notes/1.0-alpha1.md'
