# General Setup
site_name: VersionPress Documentation
site_url: 'http://127.0.0.1:8000'
docs_dir: './content'
repo_url: https://github.com/versionpress/versionpress
site_description: 'Welcome to VersionPress documentation. VersionPress itself is intuitive to use but some things like core concepts or installation details require more attention and are described here.'
copyright: 'Copyright &copy; 2018 VersionPress'

# Marketing Stuff
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extras (dependent on material theme)
extra:
  social:
    - type: 'github'
      link: 'https://github.com/versionpress'
    - type: 'twitter'
      link: 'https://twitter.com/versionpress'
  search:
    tokenizer: '[\s\-\.]+'

# Theme Config
theme:
  name: 'material'
  feature:
    tabs: true
  logo: 'img/icon.png'
  favicon: 'img/favicon.ico'
  font:
    text: '"Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif'
    code: 'Consolas, "Liberation Mono", Menlo, Courier, monospace'
  palette:
    primary: 'cyan'
    accent: 'teal'

# Nav structure
pages:
  - Home: 'index.md'
  - User:
    - Getting Started:
      - 'Getting Started Home': 'en/user/getting-started/index.md'
      - 'Basic Concepts': 'en/user/getting-started/concepts.md'
      - 'Installation and Uninstallation': 'en/user/getting-started/installation-uninstallation.md'
      - 'Configuration': 'en/user/getting-started/configuration.md'
      - 'Using VersionPress': 'en/user/getting-started/using-versionpress.md'
      - 'Developer Preview': 'en/user/getting-started/about-eap.md'
    - Feature Focus:
      - 'Feature Focus Home': 'en/user/feature-focus/index.md'
      - 'How VersionPress Works': 'en/user/feature-focus/how-versionpress-works.md'
      - 'Change Tracking': 'en/user/feature-focus/change-tracking.md'
      - 'Undo and Rollback': 'en/user/feature-focus/undo-and-rollback.md'
      - 'Searching History': 'en/user/feature-focus/searching-history.md'
      - 'External Plugins and Themes': 'en/user/feature-focus/external-plugins.md'
      - 'Custom project structure': 'en/user/feature-focus/custom-project-structure.md'
      - 'WP-CLI Commands': 'en/user/feature-focus/wp-cli.md'
      - 'Versioning Engine - Git': 'en/user/feature-focus/git.md'
      - 'Performance Considerations': 'en/user/feature-focus/performance.md'
    - Sync / Team Workflows:
      - 'Sync / Team Workflows Home': 'en/user/sync/index.md'
      - 'Concepts': 'en/user/sync/concepts.md'
      - 'Cloning a Site': 'en/user/sync/cloning.md'
      - 'Merging Sites': 'en/user/sync/merging.md'
    - 3rd Party Integrations:
      - '3rd Party Integrations Home': 'en/user/integrations/index.md'
      - 'Plugins': 'en/user/integrations/plugins.md'
      - 'Themes': 'en/user/integrations/themes.md'
      - 'Hosts': 'en/user/integrations/hosts.md'
    - Troubleshooting:
      - 'Troubleshooting Home': 'en/user/troubleshooting/index.md'
      - 'System Info Page': 'en/user/troubleshooting/system-info-page.md'
      - 'UI Not Loading': 'en/user/troubleshooting/ui-not-loading.md'
      - 'IIS': 'en/user/troubleshooting/iis.md'
  - Developer:
    - 'Developer Setup': 'en/developer/setup.md'
    - 'Plugin Support': 'en/developer/plugin-support.md'
    - 'Development Process': 'en/developer/development-process.md'
  - Release Notes:
    - 'Release Notes Home': 'en/release-notes/index.md'
    - 'Roadmap': 'en/release-notes/roadmap.md'
    - '4.0-beta Release Notes': 'en/release-notes/4.0-beta.md'
    - '4.0-alpha1 Release Notes': 'en/release-notes/4.0-alpha1.md'
    - '3.0.2 Release Notes': 'en/release-notes/3.0.2.md'
    - '3.0.1 Release Notes': 'en/release-notes/3.0.1.md'
    - '3.0 Release Notes': 'en/release-notes/3.0.md'
    - '2.2 Release Notes': 'en/release-notes/2.2.md'
    - '2.1.1 Release Notes': 'en/release-notes/2.1.1.md'
    - '2.1 Release Notes': 'en/release-notes/2.1.md'
    - '2.0.1 Release Notes': 'en/release-notes/2.0.1.md'
    - '2.0 Release Notes': 'en/release-notes/2.0.md'
    - '1.0.1 Release Notes': 'en/release-notes/1.0.1.md'
    - '1.0 Release Notes': 'en/release-notes/1.0.md'
    - '1.0-rc3 Release Notes': 'en/release-notes/1.0-rc3.md'
    - '1.0-rc2 Release Notes': 'en/release-notes/1.0-rc2.md'
    - '1.0-rc1 Release Notes': 'en/release-notes/1.0-rc1.md'
    - '1.0-beta2 Release Notes': 'en/release-notes/1.0-beta2.md'
    - '1.0-beta1 Release Notes': 'en/release-notes/1.0-beta1.md'
    - '1.0-alpha3 Release Notes': 'en/release-notes/1.0-alpha3.md'
    - '1.0-alpha2 Release Notes': 'en/release-notes/1.0-alpha2.md'
    - '1.0-alpha1 Release Notes': 'en/release-notes/1.0-alpha1.md'

# Extensions
markdown_extensions:
# PyMdown extensions https://facelessuser.github.io/pymdown-extensions/#extensions
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite: # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
      guess_lang: false
      linenums: true
  - meta # https://squidfunk.github.io/mkdocs-material/extensions/metadata/
  - toc:
      permalink: true

# Custom styles and scripts
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
