site_name: VersionPress Documentation
repo_url: https://github.com/versionpress/versionpress
site_description: 'Welcome to VersionPress documentation. VersionPress itself is intuitive to use but some things like core concepts or installation details require more attention and are described here.'
copyright: '2018 VersionPress'
pages:
- Home: 'index.md'
- Getting Started:
  - 'Getting Started Home': 'getting-started/index.md'
- Feature Focus:
  - 'Feature Focus': 'feature-focus/index.md'
theme:
    name: yeti
docs_dir: './content/en'
extra:
    version: 3.0
